dist: trusty
language: php
cache:
  directories:
  - $HOME/.composer
  - $HOME/.npm

# addons:
#   chrome: stable

php:
  - 7.2

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  global:
     - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
     - DRUPAL_VERSION='8.x'
     - DRUSH_VERSION='8.*'
     - PHPCS_VERSION='2.9.*@dev'
     - CODER_VERSION='dev-8.x-2.x'
     - DB=mysql
     - LIGHTHOUSE_API_KEY=***REMOVED***

install:
  ssh-agent -k

before_script:
  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Code sniff
  - cd $TRAVIS_BUILD_DIR
  - composer install

  # LightHouseBot
  - npm i --save-dev https://github.com/GoogleChromeLabs/lighthousebot

script:
  - test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
  - test ! -d ./html/themes/custom || find -L ./html/themes/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l

  - ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - test ! -d ./html/modules/custom || ./vendor/bin/phpcs -p --report=full ./html/modules/custom
  - # test ! -d ./html/themes/custom || ./vendor/bin/phpcs -p --report=full ./html/themes/custom

  - mysql -e 'create database drupal;'
  - cd html
  - echo "\$config_directories[CONFIG_SYNC_DIRECTORY] = '../config';" >> sites/default/default.settings.php
  - ../vendor/bin/drush --verbose -y si --existing-config --account-pass="***REMOVED***" --db-url=mysql://root:@127.0.0.1/drupal
  - cd ..
  - DTT_BASE_URL=http://localhost:8080 ./vendor/bin/phpunit --debug --colors --printer '\\Drupal\\Tests\\Listeners\\HtmlOutputPrinter'

after_success:
  - npm run lh -- http://localhost:8080
  - echo "The tests completed without errors."

after_failure:
  - echo "The tests failed. Please check the output above for problems."
