dist: focal
language: php

php:
  - 8.0

env:
  - NODE_VERSION="16.14"

# Make sure we have a recent version of docker-compose and chrome.
addons:
  apt:
    packages:
      - docker-compose
  chrome: stable

mysql:
  database: drupal
  username: root
  encoding: utf8

services:
  - mysql

# Add the specified nodejs via nvm, as Travis can only specify a single language.
install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  # - test -n "${SSH_AGENT_PID}" && ssh-agent -k

before_script:
  # Install the AWS CLI and login to the ECR. Credentials are secrets set via the UI.
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
  - aws ecr-public get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin public.ecr.aws/unocha

  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update --2

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Code sniff
  - cd $TRAVIS_BUILD_DIR
  - composer install

  # LightHouseBot
  # - npm i --save-dev https://github.com/GoogleChromeLabs/lighthousebot

  # PWMetrics
  - npm i --verbose

script:
  # PHP linting
  - set -e
  - test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
  - test ! -d ./html/themes/custom || find -L ./html/themes/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l

  # PHP CS
  - # test ! -d ./html/themes/custom || ./vendor/bin/phpcs -p --report=full ./html/themes/custom
  - test ! -d ./html/modules/custom || ./vendor/bin/phpcs -p --report=full ./html/modules/custom
  - set +e

  # Run unit, kernel tests
  - ./vendor/bin/phpunit --debug --colors --testsuite=unit

  # Drupal install
  - mysql -e "CREATE DATABASE drupal;"
  - mysql -e "CREATE USER drupal@127.0.0.1 IDENTIFIED BY 'drupal';"
  - mysql -e "GRANT ALL ON drupal.* to drupal@127.0.0.1;"

  - cd ${TRAVIS_BUILD_DIR}/html
  - ../vendor/bin/drush -y si --db-url=mysql://drupal:drupal@127.0.0.1/drupal minimal
  - ../vendor/bin/drush -y cset system.site uuid $(grep uuid ${TRAVIS_BUILD_DIR}/config/system.site.yml | awk '{print $2}')
  - ../vendor/bin/drush -y cim --source=${TRAVIS_BUILD_DIR}/config
  - ../vendor/bin/drush rs 127.0.0.1:8080 >/dev/null 2>&1 &
  - ../vendor/bin/drush php-eval 'node_access_rebuild();'
  - ../vendor/bin/drush cr
  - sleep 5

  # Test
  - cd $TRAVIS_BUILD_DIR
  - DTT_BASE_URL=http://127.0.0.1:8080 ./vendor/bin/phpunit --debug --colors --testsuite=existing-site,existing-site-javascript

after_success:
  - cd $TRAVIS_BUILD_DIR
  - # npm run lh -- http://127.0.0.1:8080
  - npm run pwmetrics -- http://127.0.0.1:8080
  - killall -9 php
  - echo "The tests completed without errors."

after_failure:
  - echo "The tests failed. Please check the output above for problems."
