<?php

use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;
use Drupal\Component\Utility\Html;
use Drupal\iasc_migrate\IascMigrateGroup;

/**
 * Implements hook_migrate_prepare_row().
 */
function iasc_migrate_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {

  switch ($migration->id()) {
    case 'upgrade_d7_node_oa_group':
    case 'upgrade_d7_node_oa_space':
      // Slugify the title then set that as the alias for the group
      $title = $row->getSourceProperty('title');
      $alias = Html::cleanCssIdentifier($title);
      $alias = '/'. strtolower($alias);
      $row->setSourceProperty('alias', $alias);

      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * Adds a user to the respective group identified.
 */
function iasc_migrate_user_insert($entity) {
  $add = (new IascMigrateGroup($entity))->addUserToGroup('field_iasc_group_space');
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * Adds a node to the respective group identified.
 */
function iasc_migrate_node_insert($entity) {
  switch ($entity->bundle()) {
    case 'action_point':
    case 'announcement':
    case 'oa_discussion_post':
    case 'oa_event':
    case 'oa_ical_importer':
    case 'oa_section':
    case 'oa_team':
    case 'oa_wiki_page':
    case 'oa_worktracker_task':
      $add = (new IascMigrateGroup($entity))->addNodeToGroup('field_iasc_audience');
      break;
  }
}
