<?php

/**
 * @file
 * IASC Services.
 */

use Drupal\facets\Entity\Facet;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\search_api\Entity\Index;
use Drupal\Taxonomy\Entity\Term;

/**
 * Implements hook_preprocess_paragraph().
 */
function iasc_service_preprocess_paragraph(&$vars) {
  $paragraph = $vars['paragraph'];
  if (!($paragraph instanceof Paragraph)) {
    return;
  }

  $bundle = $paragraph->bundle();
  switch ($bundle) {
    case 'services_landing_block':
      iasc_service_preprocess_paragraph_services_landing_block($vars);
      break;

  }
}

/**
 * Build services landing block.
 */
function iasc_service_landing_block_facets() {
  return [
    'aap_services' => 'label',
    'aap_service_coverage_region' => 'label',
    'services_relevant_hpc_stage' => 'no-sort',
    'aap_agency_initiative_or_group' => 'label',
  ];
}

/**
 * Build services landing block.
 *
 * @see html/themes/custom/iasc_common_design/templates/paragraphs/paragraph--services-landing-block.html.twig
 */
function iasc_service_preprocess_paragraph_services_landing_block(&$vars) {
  // Logic is inside template.
}

/**
 * Implements hook_token_info().
 */
function iasc_service_token_info() {
  return [
    'types' => [
      'iasc_service' => [
        'name' => t('IASC services.'),
        'description' => t('Tokens related to the service directory.'),
      ],
    ],
    'tokens' => [
      'iasc_service' => [
        'num_organizations' => [
          'name' => t('Number of organizations.'),
          'description' => t('Number of organizations in the service directory.'),
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_tokens().
 */
function iasc_service_tokens($type, $tokens, array $data, array $options, $bubbleable_metadata) {
  $replacements = [];

  if ($type == 'iasc_service') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'num_organizations':
          $replacements[$original] = iasc_service_index_num_documents();
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Get num of documents in service index.
 */
function iasc_service_index_num_documents() {
  $index = Index::load('services');
  $query = $index->query([
    'limit' => 0,
  ]);

  $results = $query->execute();
  return $results->getResultCount();
}
