definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
  user__page:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: -10
  block__admin_display:
    weight: -80
    menu_name: admin
    parent: system.admin_structure
    enabled: true
    expanded: false
  entity__node_type__collection:
    weight: -78
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  field_ui__display_mode:
    weight: -77
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__entity_queue__collection:
    weight: -76
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  flag__admin__structure__flag:
    weight: -75
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  hero__admin__structure__settings:
    weight: -74
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__media_type__collection:
    weight: -73
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__menu__collection:
    weight: -72
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__paragraphs_type__collection:
    weight: -71
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__taxonomy_vocabulary__collection:
    weight: -70
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__view__collection:
    weight: -69
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  config__conditional_field:
    weight: -68
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__hero__collection:
    enabled: false
    menu_name: admin
    parent: system.admin_content
    expanded: false
    weight: 100
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
