_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_denied: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_split: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  date_recur: 0
  date_recur_modular: 0
  datetime: 0
  datetime_range: 0
  diff: 0
  dream_block_manager: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  entityqueue: 0
  facets: 0
  facets_pretty_paths: 0
  facets_summary: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_checker: 0
  filter: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  geophp: 0
  gnode: 0
  google_tag: 0
  group: 0
  help: 0
  history: 0
  honeypot: 0
  iasc_content: 0
  iasc_hero: 0
  iasc_reliefweb: 0
  iasc_service: 0
  image: 0
  language: 0
  layout_discovery: 0
  link: 0
  linkit: 0
  maintenance200: 0
  media: 0
  media_entity_file_replace: 0
  media_library: 0
  memcache: 0
  menu_ui: 0
  node: 0
  node_view_permissions: 0
  ocha_integrations: 0
  ocha_security: 0
  ocha_viewsreference_filter: 0
  options: 0
  page_cache: 0
  paragraphs_edit: 0
  paragraphs_modal_edit: 0
  paragraphs_viewmode: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  realname: 0
  redirect: 0
  rest: 0
  search_api: 0
  search_api_attachments: 0
  search_api_db: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  seckit: 0
  select2: 0
  select2_facets: 0
  select_a11y: 0
  select_or_other: 0
  serialization: 0
  shortcut: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  spamspan: 0
  syslog: 0
  system: 0
  tablefield: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  un_date: 0
  update: 0
  user: 0
  user_expire: 0
  variationcache: 0
  views_data_export: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_submission_log: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  bartik: 0
  seven: 0
  common_design: 0
  iasc_common_design: 0
profile: minimal
