_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: false
  user__page:
    menu_name: account
    parent: ''
    weight: -10
    expanded: false
    enabled: false
  block__admin_display:
    menu_name: admin
    parent: system.admin_structure
    weight: -80
    expanded: false
    enabled: true
  entity__node_type__collection:
    menu_name: admin
    parent: system.admin_structure
    weight: -78
    expanded: false
    enabled: true
  field_ui__display_mode:
    menu_name: admin
    parent: system.admin_structure
    weight: -77
    expanded: false
    enabled: true
  entity__entity_queue__collection:
    menu_name: admin
    parent: system.admin_structure
    weight: -76
    expanded: false
    enabled: true
  flag__admin__structure__flag:
    menu_name: admin
    parent: system.admin_structure
    weight: -75
    expanded: false
    enabled: true
  hero__admin__structure__settings:
    menu_name: admin
    parent: system.admin_structure
    weight: -74
    expanded: false
    enabled: true
  entity__media_type__collection:
    menu_name: admin
    parent: system.admin_structure
    weight: -73
    expanded: false
    enabled: true
  entity__menu__collection:
    menu_name: admin
    parent: system.admin_structure
    weight: -72
    expanded: false
    enabled: true
  entity__paragraphs_type__collection:
    menu_name: admin
    parent: system.admin_structure
    weight: -71
    expanded: false
    enabled: true
  entity__taxonomy_vocabulary__collection:
    menu_name: admin
    parent: system.admin_structure
    weight: -70
    expanded: false
    enabled: true
  entity__view__collection:
    menu_name: admin
    parent: system.admin_structure
    weight: -69
    expanded: false
    enabled: true
  config__conditional_field:
    menu_name: admin
    parent: system.admin_structure
    weight: -68
    expanded: false
    enabled: true
  entity__hero__collection:
    menu_name: admin
    parent: system.admin_content
    weight: 100
    expanded: false
    enabled: false
  user__logout:
    enabled: false
    menu_name: account
    parent: ''
    weight: 10
    expanded: false
