_core:
  default_config_hash: yOPH6uEZYRHbg2OFP-bze0jGr06fI-Gr_66W-vA8Faw
report-only:
  enable: true
  directives:
    connect-src:
      base: self
      sources:
        - 'https://*.google-analytics.com'
        - 'https://analytics.google.com'
        - 'https://*.analytics.google.com'
        - 'https://*.googletagmanager.com'
    font-src:
      base: self
      sources:
        - 'data:'
        - interagencystandingcommittee.org
        - fonts.gstatic.com
    img-src:
      base: self
      sources:
        - 'data:'
        - '*.twimg.com'
        - '*.twitter.com'
        - 'https://*.google-analytics.com'
        - 'https://*.googletagmanager.com'
        - '*.ytimg.com'
        - '*.google.com'
        - mcusercontent.com
        - '*.mailchimp.com'
        - '*.gstatic.com'
    object-src:
      base: none
    script-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - www.gstatic.com
        - cdn.jsdelivr.net
        - platform.twitter.com
        - 'https://*.googletagmanager.com'
        - 'https://*.google.com'
        - '*.google-analytics.com'
        - '*.twimg.com'
    script-src-attr:
      base: self
    script-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - www.gstatic.com
        - 'https://*.googletagmanager.com'
        - 'https://*.google.com'
        - '*.google-analytics.com'
        - '*.twimg.com'
        - '*.twitter.com'
    style-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - '*.twimg.com'
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - '*.twimg.com'
        - '*.twitter.com'
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
enforce:
  enable: true
  directives:
    object-src:
      base: none
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
