auth:
  social_auth_hid:
    route: social_auth_hid.redirect_to_hid
    img_path: modules/contrib/social_auth_hid/img/hid_logo.png
post_login: /user
redirect_user_form: false
disable_admin_login: false
disabled_roles:
  administrator: '0'
  editor: '0'
  group_login: '0'
  viewer: '0'
  recommendations_editor: '0'
  space_super_admin: '0'
  focal_point: '0'
  iasc: '0'
_core:
  default_config_hash: 1tS3jCuYxV3TXQ2cq320XarjdXWprvWK5bru8DCsIUY
user_allowed: register
