_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: bca94898-6ebe-44c8-adc6-88e694da7b0e
name: IASC
mail: iasccorrespondence@un.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node/40181
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
