<?php

/**
 * @file
 * Contains facets.module.
 */

/**
 * Implements hook_theme().
 */
function select_a11y_theme($existing, $type, $theme, $path) {
  return [
    'select_a11y_facet' => [
      'variables' => [
        'facet' => NULL,
        'items' => [],
        'title' => '',
        'list_type' => 'ul',
        'wrapper_attributes' => [],
        'attributes' => [],
        'empty' => NULL,
        'context' => [],
      ],
    ],
  ];
}
