name: Build develop docker image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker develop image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        docker build . --file docker/Dockerfile --tag unocha/iasc-site:develop
        docker push unocha/iasc-site:develop
    - name: Ping Flowdock
      uses: UN-OCHA/gha-flowfock-notify@master
      env:
        FLOWDOCK_TOKEN: ${{ secrets.FLOWDOCK_TOKEN }}
        FLOWDOCK_MESSAGE: 'Built and pushed a new develop `unocha/iasc-site` image.'
